#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY


if [ $(pgrep Xorg) ];then
    xrdb ~/.config/X11/Xresources &# Uncomment to use Xresources colors/settings on startup
    xcompmgr &		# xcompmgr for transparency
    xset r rate 300 50 &	# Speed xrate up
    unclutter &		# Remove mouse when idle
    ! [ "$(pgrep mpd-module-up)" ] && mpd-module-update  &	# Check for when to update the mpd module
    # this is no more required because of interception tools : see below
    # remaps &        # run the remaps script, switching caps/esc and more; check it for more info
elif ! [ "$(pidof sway)" ] && ! [ "$(pidof waybar)" ] && ! [ "$(pidof wayfire)" ];then
    waybar &
fi

! [ $(pidof sway) ] && setbg &          # set the background with the `setbg` script
! [ "$(pgrep clipmangr)" ] && clipmangr daemon &
! [ "$(pidof mpd)" ] && mpd &          # music player daemon-you might prefer it as a service though
! [ "$(pidof dwl)" ] && pgrep dunst && { pkill dunst && dunst & } || dunst >/dev/null &         # dunst for notifications
! [ "$(pidof udevmon)" ] && sudo nice -20 udevmon  2> ~/.config/interception-tools/udevmon.err 1> ~/.config/interception-tools/udevmon.log &
